In [7]:
import numpy as np
import torch
import imageio
img_arr = imageio.imread('../data/p1ch4/image-dog/bobby.jpg')
img_arr.shape

(720, 1280, 3)

In [9]:
img = torch.from_numpy(img_arr)
out = img.permute(2, 0 , 1)
out.shape

torch.Size([3, 720, 1280])

In [13]:
batch_size = 100
batch = torch.zeros(batch_size, 3, 256, 256, dtype = torch.uint8)

In [15]:
import os
data_dir = '../data/p1ch4/image-cats'
filenames = [name for name in os.listdir(data_dir) if os.path.splitext(name)[-1] == '.png']

for i, filename in enumerate(filenames):
    img_arr = imageio.imread(os.path.join(data_dir,filename))
    img_t = torch.from_numpy(img_arr)
    img_t = img_t.permute(2,0,1)
    img_t = img_t[:3]
    batch[i] = img_t
batch.shape

torch.Size([100, 3, 256, 256])

In [28]:
n = batch.shape[1]
for c in range(n):
    mean = torch.mean(batch[:,c])
    std = torch.std(batch[:,c])
    batch[:,c]= (batch[:,c ] - mean) / std
batch[1,2]

tensor([[ 3.6971,  2.8476,  2.3379,  ...,  0.1858,  0.1858,  0.1292],
        [ 3.6405,  2.9042,  2.3379,  ...,  0.1858,  0.1858,  0.1858],
        [ 3.6405,  3.0175,  2.3379,  ...,  0.1858,  0.1858,  0.1858],
        ...,
        [ 1.6016,  0.9220,  0.5256,  ...,  0.8088,  0.8088,  0.8088],
        [ 0.4690, -0.0407,  1.8282,  ...,  0.8088,  0.8088,  0.8654],
        [ 0.9220,  1.9414,  1.0919,  ...,  0.8088,  0.8654,  0.9220]])

In [33]:
import imageio
dir_path = '../data/p1ch4/volumetric-dicom/2-LUNG 3.0  B70f-04083'
vol_arr = imageio.volread(dir_path, 'DICOM')
vol_arr.shape

Reading DICOM (examining files): 1/99 files (1.0%42/99 files (42.4%99/99 files (100.0%)
  Found 1 correct series.
Reading DICOM (loading data): 44/99  (44.493/99  (93.999/99  (100.0%)


(99, 512, 512)

In [37]:
vol = torch.from_numpy(vol_arr).float()
vol = torch.unsqueeze(vol, 1)
vol = torch.unsqueeze(vol, 2)
vol.shape

torch.Size([99, 1, 1, 512, 512])

In [42]:
import csv
wine_path = '../data/p1ch4/tabular-wine/winequality-white.csv'
wine_np = np.loadtxt(wine_path, dtype = np.float32, delimiter=";", skiprows = 1)
wine_np

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [100]:
col_lis = next(csv.reader(open(wine_path) ,delimiter=";"))
col_lis

['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol',
 'quality']

In [57]:
wineq = torch.from_numpy(wine_np)
wineq.shape

torch.Size([4898, 12])

In [61]:
data = wineq[:,:-1]
data, data.shape

(tensor([[ 7.0000,  0.2700,  0.3600,  ...,  3.0000,  0.4500,  8.8000],
         [ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
         [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
         ...,
         [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
         [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000],
         [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]]),
 torch.Size([4898, 11]))

In [64]:
target = wineq[:,-1]
target, target.shape


(tensor([6., 6., 6.,  ..., 6., 7., 6.]), torch.Size([4898]))

In [65]:
target = wineq[:,-1].long()
target

tensor([6, 6, 6,  ..., 6, 7, 6])

In [66]:
target_onehot = torch.zeros(target.shape[0],10)
a = target_onehot.scatter_(1,target.unsqueeze(1),1.0)
a, a.shape

(tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 1., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]),
 torch.Size([4898, 10]))

In [70]:
data_mean = torch.mean(data, dim=0)
data_mean

tensor([6.8548e+00, 2.7824e-01, 3.3419e-01, 6.3914e+00, 4.5772e-02, 3.5308e+01,
        1.3836e+02, 9.9403e-01, 3.1883e+00, 4.8985e-01, 1.0514e+01])

In [74]:
data_var = torch.var(data, dim=0)
data_var

tensor([7.1211e-01, 1.0160e-02, 1.4646e-02, 2.5726e+01, 4.7733e-04, 2.8924e+02,
        1.8061e+03, 8.9455e-06, 2.2801e-02, 1.3025e-02, 1.5144e+00])

In [89]:
data_nor = data - data_mean
data_nor

tensor([[ 6.1561,  0.1692,  0.2390,  ...,  2.8490,  0.3359,  7.5694],
        [ 5.4561,  0.1992,  0.2190,  ...,  3.1490,  0.3759,  8.2694],
        [ 7.2561,  0.1792,  0.2790,  ...,  3.1090,  0.3259,  8.8694],
        ...,
        [ 5.6561,  0.1392,  0.0690,  ...,  2.8390,  0.3459,  8.1694],
        [ 4.6561,  0.1892,  0.1790,  ...,  3.1890,  0.2659, 11.5694],
        [ 5.1561,  0.1092,  0.2590,  ...,  3.1090,  0.2059, 10.5694]])

In [101]:
bad_data = data[target<=3]
mid_data = data[(target>3) & (target<7)]
high_data = data[target>=7]
bad_mean = torch.mean(bad_data, dim=0)
mid_mean = torch.mean(mid_data, dim=0)
high_mean = torch.mean(high_data, dim=0)
for i, args in enumerate(zip(col_lis, bad_mean, mid_mean, high_mean)):
    print('{:2} {:20} {:6.2f} {:6.2f} {:6.2f}'.format(i,*args))

 0 fixed acidity          7.60   6.89   6.73
 1 volatile acidity       0.33   0.28   0.27
 2 citric acid            0.34   0.34   0.33
 3 residual sugar         6.39   6.71   5.26
 4 chlorides              0.05   0.05   0.04
 5 free sulfur dioxide   53.33  35.42  34.55
 6 total sulfur dioxide 170.60 141.83 125.25
 7 density                0.99   0.99   0.99
 8 pH                     3.19   3.18   3.22
 9 sulphates              0.47   0.49   0.50
10 alcohol               10.34  10.26  11.42


In [103]:
t = 141.83
t_d = data[:,6]
p_id = torch.lt(t_d, t)
p_id.shape, p_id.dtype, p_id.sum()

(torch.Size([4898]), torch.bool, tensor(2727))

In [106]:
actual = target> 5
actual.shape, actual.dtype, actual.sum()

(torch.Size([4898]), torch.bool, tensor(3258))

In [110]:
match = torch.sum(actual & p_id).item()
n_pr = torch.sum(p_id).item()
n_ac = torch.sum(actual).item()
match, match / n_pr, match / n_ac

(2018, 0.74000733406674, 0.6193984039287906)

In [130]:
bike_np = np.loadtxt('../data/p1ch4/bike-sharing-dataset/hour-fixed.csv',dtype = np.float32,delimiter=',',skiprows=1,converters ={1: lambda x : float(x[8:10])})
bikes = torch.from_numpy(bike_np)
bikes.shape

torch.Size([17520, 17])

In [124]:
daily = bikes.view(-1,24,bikes.shape[1])
daily.shape

torch.Size([730, 24, 17])

In [129]:
daily = daily.transpose(1,2)
daily.shape

torch.Size([730, 17, 24])

In [139]:
first_day = bikes[:24].long()
weather_onehot = torch.zeros(24,4)
first_day[:,9]

tensor([1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2])

In [141]:
weather_onehot.scatter_(1,first_day[:,9].unsqueeze(1).long()-1,1.0)

tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.]])

In [147]:
torch.cat((bikes[:24],weather_onehot), 1)[:1]

tensor([[ 1.0000,  1.0000,  1.0000,  0.0000,  1.0000,  0.0000,  0.0000,  6.0000,
          0.0000,  1.0000,  0.2400,  0.2879,  0.8100,  0.0000,  3.0000, 13.0000,
         16.0000,  1.0000,  0.0000,  0.0000,  0.0000]])

In [151]:
daily_onehot = torch.zeros(daily.shape[0],4,daily.shape[2])
daily_onehot.shape

torch.Size([730, 4, 24])

In [154]:
daily_onehot.scatter_(1,daily[:,9,:].long().unsqueeze(1)-1,1.0)


tensor([[[1., 1., 1.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 1., 1., 1.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0

In [158]:
daily = torch.cat((daily,daily_onehot),dim =1)

In [160]:
daily[:,9,:] = (daily[:,9,]-1.0) / 3.0

In [162]:
temp = daily[:,10,:]
temp_min = torch.min(temp)
temp_max = torch.max(temp)
daily[:,10,:] = (daily[:,10,:] - temp_min) / (temp_max - temp_min)

In [165]:
b = torch.tensor([[[3, 2], [1, 4]], [[5, 6], [7, 8]]])
q = torch.sum(b, dim =0)
print(q)
s = torch.sum(b, dim =1)
print(s)

tensor([[ 8,  8],
        [ 8, 12]])
tensor([[ 4,  6],
        [12, 14]])


In [173]:
with open('../data/p1ch4/jane-austen/1342-0.txt', encoding='utf8') as f:
    text = f.read()

In [175]:
lines = text.split('\n')
line = lines[200]
line

'“Impossible, Mr. Bennet, impossible, when I am not acquainted with him'

In [183]:
letter_t = torch.zeros(len(line),128)
letter_t.shape

torch.Size([70, 128])

In [179]:
for i, letter in enumerate(line.lower().strip()):
    letter_index = ord(letter) if ord(letter)<128 else 0
    letter_t[i][letter_index] = 1


In [192]:
def clean_word(input):
    punctuation = '.,;:"!?“”_-'
    word_list = input.lower().split()
    word_list = [word.strip(punctuation) for word in word_list]
    return word_list
words_line = clean_word(line)
line , words_line

('“Impossible, Mr. Bennet, impossible, when I am not acquainted with him',
 ['impossible',
  'mr',
  'bennet',
  'impossible',
  'when',
  'i',
  'am',
  'not',
  'acquainted',
  'with',
  'him'])

In [194]:
word_list = sorted(set(clean_word(text)))
word_dict = {word: i for (i,word) in enumerate(word_list)}
len(word_dict), word_dict['impossible']

(7261, 3394)

In [195]:
word_t = torch.zeros(len(words_line),len(word_dict))
for i, word in enumerate(words_line):
    word_index = word_dict[word]
    word_t[i][word_index] = 1
    print('{} {} {}'.format(i, word_index, word))

0 3394 impossible
1 4305 mr
2 813 bennet
3 3394 impossible
4 7078 when
5 3315 i
6 415 am
7 4436 not
8 239 acquainted
9 7148 with
10 3215 him
